### ISSUE TITLE
Incorrect folder structure. Folder needs deleted.

### ISSUE THREAD

**Issue by Squatchyadoin** [buck-kristen/charcoaled#1]
Charcoaled/src  5/13/2015 - Initial commit to repository    a day ago

We pushed this directory up together yesterday. I believe it's incorrect and think it needs deleted. I cannot figure out how to delete it. Maybe you can as the repository owner.

**Comment by buck-kristen** [comment]
Why do you think it is incorrect? I don't want to delete anything unless we are sure it won't impact our project. Maybe we can ask the instructor if the file folder structure is incorrect- he responds quickly.
